/**
 * investmentScore.service.js
 * ---------------------------------------------------
 * Deterministic Investment Score calculation for PlotWise AI.
 *
 * The score is NEVER generated by the AI model. It is always calculated
 * here, from structured numeric inputs, using a fixed, documented,
 * configurable weighting formula. The AI layer (gemini.service.js) is only
 * ever given the OUTPUT of this calculation and asked to explain it in
 * plain language — it cannot alter the number itself.
 * ---------------------------------------------------
 */

// Weights must sum to 1. Keep this exported so the /methodology page and
// tests can reference the exact same source of truth as the backend.
export const SCORE_WEIGHTS = Object.freeze({
  infrastructure: 0.25,
  connectivity: 0.2,
  employment: 0.15,
  development: 0.15,
  demand: 0.15,
  riskAdjustment: 0.1, // applied to (100 - riskScore)
});

/**
 * @param {Object} inputs
 * @param {number} inputs.infrastructureScore 0-100
 * @param {number} inputs.connectivityScore 0-100
 * @param {number} inputs.employmentScore 0-100
 * @param {number} inputs.developmentScore 0-100
 * @param {number} inputs.demandScore 0-100
 * @param {number} inputs.riskScore 0-100 (higher = riskier)
 * @returns {number} integer score 0-100
 */
export function calculateInvestmentScore(inputs) {
  const {
    infrastructureScore = 0,
    connectivityScore = 0,
    employmentScore = 0,
    developmentScore = 0,
    demandScore = 0,
    riskScore = 0,
  } = inputs;

  const raw =
    infrastructureScore * SCORE_WEIGHTS.infrastructure +
    connectivityScore * SCORE_WEIGHTS.connectivity +
    employmentScore * SCORE_WEIGHTS.employment +
    developmentScore * SCORE_WEIGHTS.development +
    demandScore * SCORE_WEIGHTS.demand +
    (100 - riskScore) * SCORE_WEIGHTS.riskAdjustment;

  return Math.round(clamp(raw, 0, 100));
}

export function riskLabelFromScore(riskScore) {
  if (riskScore <= 33) return "Low";
  if (riskScore <= 66) return "Medium";
  return "High";
}

export function growthPotentialFromScore(totalScore) {
  if (totalScore >= 85) return "Very High";
  if (totalScore >= 70) return "High";
  if (totalScore >= 50) return "Moderate";
  return "Low";
}

/**
 * Produces short, human-readable, rules-based strengths/risks purely from
 * the numeric inputs. This is deterministic and does NOT require AI - it
 * exists so the app is fully usable even if the Gemini API is unavailable
 * or unconfigured (see gemini.service.js fallback).
 */
export function deriveStrengthsAndRisks(area, infrastructureProjects = []) {
  const strengths = [];
  const risks = [];

  if (area.connectivityScore >= 80) strengths.push("Strong existing and planned connectivity to key employment hubs");
  if (area.infrastructureScore >= 80) strengths.push("High concentration of infrastructure development activity");
  if (area.employmentScore >= 75) strengths.push("Notable employment and commercial activity nearby");
  if (area.developmentScore >= 75) strengths.push("Active real-estate and construction development in the area");
  if (area.demandScore >= 75) strengths.push("High buyer/tenant demand signals relative to comparable areas");

  const metro = infrastructureProjects.filter((p) => p.type === "metro");
  const highway = infrastructureProjects.filter((p) => p.type === "highway");
  const it = infrastructureProjects.filter((p) => p.type === "it_park_sez" || p.type === "industrial");

  if (metro.some((p) => p.status === "under_construction" || p.status === "approved")) {
    strengths.push("Upcoming metro/rail connectivity in progress or approved");
  }
  if (highway.length > 0) {
    strengths.push("Highway or expressway connectivity improvements identified in the area");
  }
  if (it.length > 0) {
    strengths.push("Presence of IT parks, SEZs, or industrial development driving employment demand");
  }

  if (area.riskScore >= 60) risks.push("Higher uncertainty due to dependency on proposed or early-stage projects");
  if (area.developmentScore >= 80) risks.push("Elevated current prices possible due to already-active development");
  if (infrastructureProjects.some((p) => p.status === "proposed")) {
    risks.push("Some nearby projects are only proposed and not yet approved or funded");
  }
  if (infrastructureProjects.some((p) => p.status === "under_construction")) {
    risks.push("Construction timelines for in-progress projects may shift");
  }
  if (area.riskScore >= 40 && risks.length === 0) {
    risks.push("General market and execution risk applies, as with any real-estate investment");
  }

  return {
    strengths: strengths.length ? strengths.slice(0, 5) : ["Balanced fundamentals across measured growth factors"],
    risks: risks.length ? risks.slice(0, 5) : ["No elevated risk signals identified in available data"],
  };
}

function clamp(value, min, max) {
  return Math.min(Math.max(value, min), max);
}
